name: Build macOS App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Trigger on version tags like v1.0.0
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write  # Needed to create releases
      actions: read    # Needed to read workflow files

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific version if needed, e.g., '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build the application
      run: |
        source venv/bin/activate
        pyinstaller TyosopimusApp.spec
        # List contents to verify what was created
        ls -la dist/
        # Create a zip archive of the .app bundle
        cd dist
        zip -r Työsopimuskone_macOS.zip Työsopimuskone.app
        ls -la
        cd ..


    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Työsopimuskone-macOS
        path: dist/Työsopimuskone_macOS.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/Työsopimuskone_macOS.zip
        body: |
          ## Työsopimuskone ${{ github.ref_name }}
          
          ### Lataa macOS-sovellus
          - Lataa `Työsopimuskone_macOS.zip`
          - Pura zip-tiedosto
          - Käynnistä `Työsopimus
