name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific version if needed, e.g., '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build the application
      run: |
        source venv/bin/activate
        pyinstaller --noconfirm --onefile --windowed --name TyosopimusKone main.py
        # List contents to verify what was created
        ls -la dist/
        # Create a zip archive of the executable
        cd dist && zip TyosopimusKone_macOS.zip TyosopimusKone && cd ..


    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TyosopimusKone-macOS
        path: dist/TyosopimusKone_macOS.zip
