name: Build macOS App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Trigger on version tags like v1.0.0
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write  # Needed to create releases
      actions: read    # Needed to read workflow files

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific version if needed, e.g., '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build the application
      run: |
        source venv/bin/activate
        pyinstaller --windowed --onefile --name TyosopimusApp --icon=assets/app_icon.icns main.py
        # List contents to verify what was created
        ls -la dist/
        # Create a zip archive of the executable
        cd dist
        zip TyosopimusKone_macOS.zip TyosopimusKone
        ls -la
        cd ..


    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TyosopimusKone-macOS
        path: dist/TyosopimusKone_macOS.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/TyosopimusKone_macOS.zip
        body: |
          ## Työsopimuskone ${{ github.ref_name }}
          
          ### Lataa macOS-sovellus
          - Lataa `TyosopimusKone_macOS.zip`
          - Pura zip-tiedosto
          - Käynnistä `TyosopimusKone`
          
          ### Ominaisuudet
          - Luo suomalaisia työsopimuksia
          - PDF-vienti
          - Sopimusten tallennus ja lataus
          - Live HTML -esikatselu
          - Sopimuspäivämäärä-kenttä
          
          **Huom:** macOS saattaa varoittaa tuntemattomasta kehittäjästä. Klikkaa "Avaa silti" Järjestelmäasetuksista.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
